DROP DATABASE IF EXISTS typoteka;

CREATE DATABASE typoteka
  WITH
  OWNER = typoteka
  ENCODING = 'UTF8'
  TEMPLATE = template0
  LC_COLLATE = 'C'
  LC_CTYPE = 'C'
  CONNECTION LIMIT = -1;

GRANT ALL ON DATABASE typoteka TO typoteka;
