HEAD /posts HTTP/1.1
Host: jsonplaceholder.typicode.com

###

GET /posts HTTP/1.1
Host: jsonplaceholder.typicode.com

###

POST /posts HTTP/1.1
Host: jsonplaceholder.typicode.com
Content-Type: application/json

{
  "title": "Новая публикация",
  "body": "Текст публикации",
  "userId": 31337
}

### Получить все комментарии к публикациям

GET https://jsonplaceholder.typicode.com/comments HTTP/1.1
Content-Type: application/json

###

GET https://jsonplaceholder.typicode.com/comments?postId=1 HTTP/1.1
Content-Type: application/json

### проверка Роутера

### главная страница
GET http://localhost:8080

### регистрация
GET http://localhost:8080/register

### Логин
GET http://localhost:8080/login

### поиск
GET http://localhost:8080/search

### мои публикации
GET http://localhost:8080/my

### Комментарии к публикациям
GET http://localhost:8080/my/comments

### Категории
GET http://localhost:8080/my/categories

### страница публикации
GET http://localhost:8080/articles/5

### публикации в определённой категории
GET http://localhost:8080/articles/category/8

### страница создания новой публикации
GET http://localhost:8080/articles/add

### редактирование публикации
GET http://localhost:8080/articles/edit/4
