### Проверка REST сервера
GET http://localhost:3000/posts

### Проверка Роутера Шаблонизатора

### главная страница
GET http://localhost:8080

### регистрация
GET http://localhost:8080/register

### Логин
GET http://localhost:8080/login

### поиск
GET http://localhost:8080/search

### мои публикации
GET http://localhost:8080/my

### Комментарии к публикациям
GET http://localhost:8080/my/comments

### Категории
GET http://localhost:8080/my/categories

### страница публикации
GET http://localhost:8080/articles/5

### публикации в определённой категории
GET http://localhost:8080/articles/category/8

### страница создания новой публикации
GET http://localhost:8080/articles/add

### редактирование публикации
GET http://localhost:8080/articles/edit/4
