## Проверка Front

### * главная страница
GET http://localhost:8080

### регистрация
GET http://localhost:8080/register

### Логин
GET http://localhost:8080/login

### * поиск
GET http://localhost:8080/search

### * Мои публикации
GET http://localhost:8080/my

### * Мои комментарии к публикациии
GET http://localhost:8080/my/comments

### * Мои категории
GET http://localhost:8080/my/categories

### * Страница публикации
GET http://localhost:8080/articles/5

### публикации в определённой категории
GET http://localhost:8080/articles/category/8

### * Страница создания новой публикации
GET http://localhost:8080/articles/add

### * Редактирование публикации
GET http://localhost:8080/articles/edit/4

## Проверка сервиса REST API

### Возвращает список публикаций
GET http://localhost:8000/api/articles

### Возвращает полную информацию о публикации
GET http://localhost:8000/api/articles/1

### Создаёт новую публикацию
POST http://localhost:8000/api/articles
Content-Type: application/json

{
  "title": "Небо каким цветом?",
  "createDate": "2022-05-10T22:09:45.448Z",
  "announce": "О Небе",
  "fulltext": "Альбом стал настоящим открытием года.",
  "category": "Небо"
}

### Редактирует определённую публикацию
PUT http://localhost:8000/api/articles/5nKQH2
Content-Type: application/json

{
  "title": "Теперь новый заголовок!",
  "category": "Категория"
}

### Удаляет определённую публикацию
DELETE http://localhost:8000/api/articles/aFyh1W

### Возвращает список комментариев определённой публикации;
GET http://localhost:8000/api/articles/1/comments

### Удаляет из определённой публикации комментарий с идентификатором;
DELETE http://localhost:8000/api/articles/1/comments/1

### Создаёт новый комментарий;
POST http://localhost:8000/api/articles/5ywLgb/comments
Content-Type: application/json

{
  "text": "HTML Academy"
}

### Возвращает результаты поиска
GET /api/search?query=

### Возвращает список категорий;
GET http://localhost:8000/api/categories
